import numpy as np
from scipy.special import gamma

def saltation_model(f, D, H, W, theta, r0, qb=None, vc0=None, D50=None, tau_c50=None, epsilon=None,
                    Q0=None, eta=None):
    '''
    This saltation model calculates PSD generated by bedload transport (Tsai et al., 2012), assuming
    all fluvial bedload particle impact vertically and elastically onto the riverbed.

    Args:
        f : Frequency window (Hz).
        D : Grain size diameter (m).
        H : Water depth (m).
        theta : channel slope (-).
        r0 : Source-receiver distance, which is the distance from the river thalweg to a seismic sensor (m).
        qb : bedload flux per unit width (m2/s)
        D50 : Median grain size diameter (m).
        tau_c50 : Dimentionless critical shear stress for incipient motion (of D50) (-).
        vc0 : Phase velocity at reference frequency (1Hz) (m/s).
        epsilon : frequency exponent (-)
        Q0 : Quality factor at reference frequency (1Hz) (-).
        eta : Quality factor exponent (-).

    Returns:
        Power-spectral density of seismic velocity signal.
    '''

    