import numpy as np
from scipy.special import gamma
from typing import Optional, Union
from seismic_bedload.abc_class import Turbulence
from seismic_bedload.models import SedimentParams, SeismicParams


class TurbulenceModel(Turbulence):
    """
    Turbulence model: PSD generated by turbulent flow in a river
    (Gimbert et al., 2014).

    The model predicts ground velocity PSD from hydraulic and sediment
    parameters without invoking bedload particle impacts — it captures
    the seismic signature of the flow itself.
    """

    # Model constants (Gimbert et al. 2014 / Lamb et al. 2008)
    K: float = 0.5       # von Kármán-related prefactor
    C: float = 0.5       # empirical constant
    X1r: float = None    # roughness sublayer reference height; set to ks/2 in _psd
    N11: float = 0.6     # horizontal coupling coefficient
    N12: float = 0.8     # horizontal coupling coefficient
    alpha1: float = 0.12  # from Lamb et al. 2008
    alpha2: float = 0.2

    def __init__(
        self,
        sediment_params: Optional[SedimentParams] = None,
        seismic_params: Optional[SeismicParams] = None,
    ):
        self.sediment_params = sediment_params or SedimentParams()
        self.seismic_params = seismic_params or SeismicParams()

    def calculate_seismic_properties(
        self, f: np.ndarray, r0: float
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        """Return phase velocity vc, group velocity vu, and attenuation chi."""
        sp = self.seismic_params
        vc = sp.vc0 * (f / sp.f0) ** (-sp.zeta)
        vu = vc / (1 + sp.zeta)
        beta = (
            2 * np.pi * r0 * (1 + sp.zeta)
            * f ** (1 + sp.zeta - sp.eta)
            / (sp.vc0 * sp.Q0 * sp.f0 ** (sp.zeta - sp.eta))
        )
        chi = (
            2 * np.log(1 + 1 / beta) * np.exp(-2 * beta)
            + (1 - np.exp(-beta)) * np.exp(-beta) * np.sqrt(2 * np.pi / beta)
        )
        return vc, vu, chi

    # Grain-size modulation  Phi(D)
    # currently not used in forward_psd, but implemented here for potential use in future extensions
    def _grain_size_filter(
        self,
        f: Union[float, np.ndarray],
        D: np.ndarray,
        D50: float,
        H: float,
        pdf: Optional[np.ndarray] = None,
        Dstd: float = 0.52,
    ) -> float:
        """
        Compute the grain-size modulation integral phi_D.

        Parameters
        ----------
        f     : frequency (scalar or array); when scalar, ki_fl is 1-D over D.
        D     : grain diameter array [m]
        D50   : median grain size [m]
        H     : flow depth [m]
        pdf   : grain-size probability density (must integrate to ~1 over D).
                If None, uses the raised-cosine distribution with width Dstd.
        Dstd  : log-space width parameter for raised-cosine PDF (default 0.52).
        """
        if pdf is None:
            s = Dstd / np.sqrt(1 / 3 - 2 / np.pi**2)
            pdf = (
                (1 / (2 * s))
                * (1 + np.cos(np.pi * (np.log(D) - np.log(D50)) / s))
                / D
            )
            # zero outside the support
            mask = np.abs(np.log(D) - np.log(D50)) > s
            pdf = np.where(mask, 0.0, pdf)

        ks = 3 * D50
        u_star = np.sqrt(self.sediment_params.g * H * np.sin(np.arctan(1.0)))
        # fc is the corner frequency per grain size (scalar f version handled below)
        X1r_val = ks / 2
        cu_X1r = (X1r_val / (self.alpha1 * ks)) * (1 - X1r_val / (2 * ks) * ks / H)

        fc = cu_X1r * u_star / D  # shape: (len(D),)

        # ki_fl shape depends on f:
        # scalar f → (len(D),); array f → broadcast handled by caller
        ki_fl = 1.0 / (1.0 + (2.0 * np.asarray(f)[..., np.newaxis] / fc) ** (4 / 3))
        # ki_fl: (..., len(D))
        # integrate over D: phi_D has shape (...)
        phi_D = np.trapezoid(pdf * D**2 * ki_fl**2, D, axis=-1)
        return phi_D

    # Core PSD (I commented this out as this is not working for the
    # first time, but I want to keep it here for future debugging and potential use in forward_psd)


    # def _psd(
    #     self,
    #     f: np.ndarray,
    #     D: Union[float, np.ndarray],
    #     W: float,
    #     H: float,
    #     theta: float,
    #     r0: float,
    #     D50: Optional[float] = None,
    #     Dstd: float = 0.52,
    #     pdf: Optional[np.ndarray] = None,
    # ) -> np.ndarray:
    #     """
    #     PSD from turbulence for a single flow depth H.

    #     Parameters
    #     ----------
    #     f     : frequency array [Hz]
    #     D     : grain diameter(s) [m] — used for grain-size modulation
    #     W     : channel width [m]
    #     H     : flow depth [m]
    #     theta : channel slope [degrees]  (same convention as MATLAB sind/cosd)
    #     r0    : sensor-to-source distance [m]
    #     D50   : median grain size [m]; defaults to D if scalar
    #     Dstd  : log-space width of raised-cosine grain PDF
    #     pdf   : explicit grain-size PDF (overrides raised-cosine)
    #     """
    #     f = np.asarray(f)
    #     D = np.atleast_1d(np.asarray(D, dtype=float))

    #     if D50 is None:
    #         D50 = float(D[0]) if D.size == 1 else float(np.median(D))

    #     sp = self.seismic_params
    #     sd = self.sediment_params

    #     # --- seismic propagation ---
    #     vc, vu, chi = self.calculate_seismic_properties(f, r0)

    #     # --- hydraulics ---
    #     ks = 3 * D50
    #     u_star = np.sqrt(sd.g * H * np.sin(np.radians(theta)))

    #     # --- turbulence structure parameters (Gimbert 2014 Eq. 8, 33) ---
    #     X1r_val = ks / 2
    #     cu_X1r = (X1r_val / (self.alpha1 * ks)) * (
    #         1 - (X1r_val / (2 * ks)) * (ks / H)
    #     )
    #     cu_ks = (ks / (self.alpha1 * ks)) * (1 - (ks / (2 * ks)) * (ks / H))
    #     c_sigma = self.alpha2 * (5.62 * np.log10(H / ks) + 4)

    #     zeta_Hks = (cu_ks ** (1 / 3) * cu_X1r ** (4 / 3) * c_sigma ** (2 / 3)) ** 2

    #     # --- grain-size modulation phi_D ---
    #     # Pass actual u_star for corner frequency rather than unit u — override
    #     # fc inside _grain_size_filter using the correct shear velocity.
    #     # (Re-implement fc here to use local u_star, not a unit placeholder.)
    #     fc = cu_X1r * u_star / D   # (n_D,)
    #     ki_fl = 1.0 / (1.0 + (2.0 * f[:, np.newaxis] / fc[np.newaxis, :]) ** (4 / 3))
    #     # ki_fl: (n_f, n_D)

    #     if pdf is None:
    #         s = Dstd / np.sqrt(1 / 3 - 2 / np.pi**2)
    #         log_ratio = np.log(D) - np.log(D50)
    #         pdf_arr = np.where(
    #             np.abs(log_ratio) <= s,
    #             (1 / (2 * s)) * (1 + np.cos(np.pi * log_ratio / s)) / D,
    #             0.0,
    #         )
    #     else:
    #         pdf_arr = np.asarray(pdf)

    #     phi_D = np.trapezoid(pdf_arr * D**2 * ki_fl**2, D, axis=-1)  # (n_f,)

    #     # --- PSD (Gimbert 2014 Eq. 34) ---
    #     zeta = sp.zeta
    #     PSD = (
    #         (self.N11**2 + self.N12**2)
    #         * (self.K * W / 3 / ks ** (2 / 3))
    #         * (sd.rho_f / sd.rho_s) ** 2
    #         * (1 + zeta) ** 2
    #         / (sp.f0 ** (5 * zeta) * sp.vc0**5)
    #         * zeta_Hks
    #         * chi
    #         * phi_D
    #         * f ** (4 / 3 + 5 * zeta)
    #         * self.C**2
    #         * u_star ** (14 / 3)
    #     )
    #     return PSD

    def _psd(
        self,
        f: np.ndarray,
        D: Union[float, np.ndarray],
        W: float,
        H: float,
        theta: float,
        r0: float,
        D50: Optional[float] = None,
        Dstd: float = 0.52,
        pdf: Optional[np.ndarray] = None,
    ) ->     np.ndarray:

        f = np.asarray(f)
        D = np.atleast_1d(np.asarray(D, dtype=float))

        if D50 is None:
            D50 = float(D[0]) if D.size == 1 else float(np.median(D))

        sp = self.seismic_params
        sd = self.sediment_params

        # seismic velocity and attenuation
        vc, vu, chi = self.calculate_seismic_properties(f, r0)

        # (theta) is dimensionless
        ks = 3 * D50
        u = np.sqrt(sd.g * H * theta)

        # (Gimbert 2014)
        X1r = ks / 2
        cu_X1r = (X1r / (self.alpha1 * ks)) * (1 - (X1r / (2 * ks)) * (ks / H))
        cu_ks  = (ks  / (self.alpha1 * ks)) * (1 - (ks  / (2 * ks)) * (ks / H))
        c_sigma = self.alpha2 * (5.62 * np.log10(H / ks) + 4)

        zeta_Hks = (cu_ks ** (1/3) * cu_X1r ** (4/3) * c_sigma ** (2/3)) ** 2

        # grain size PDF (raised cosine, same as the MATLAB version)
        if pdf is None:
            s = Dstd / np.sqrt(1/3 - 2/np.pi**2)
            log_ratio = np.log(D) - np.log(D50)
            pdf_arr = np.where(
                np.abs(log_ratio) <= s,
                (1 / (2 * s)) * (1 + np.cos(np.pi * log_ratio / s)) / D,
                0.0,
            )
        else:
            pdf_arr = np.asarray(pdf)

        #  MATLAB uses u2_X1r = cu_X1r * u, fc = u2_X1r / D ---
        u2_X1r = cu_X1r * u                        # scalar
        fc = u2_X1r / D                             # (n_D,)

        # ki_fl: (n_f, n_D) — outer product of f and 1/fc
        ki_fl = 1.0 / (1.0 + (2.0 * f[:, np.newaxis] / fc[np.newaxis, :]) ** (4/3))

        # phiD: integrate over D for each f to (n_f,)
        phiD = np.trapezoid(pdf_arr * D**2 * ki_fl**2, D, axis=-1)
        zeta = sp.zeta
        
        PSD = (
            (self.N11**2 + self.N12**2)
            * (self.K * W / 3 / ks**(2/3))
            * (sd.rho_f / sd.rho_s)**2
            * (1 + zeta)**2
            / (sp.f0**(5 * zeta) * sp.vc0**5)
            * zeta_Hks
            * chi
            * phiD
            * f**(4/3 + 5*zeta)
            * self.C**2
            * u**(14/3)
        )
        return PSD

    def forward_psd(
        self,
        f: np.ndarray,
        D: Union[float, np.ndarray],
        W: float,
        H: float,
        theta: float,
        r0: float,
        D50: Optional[float] = None,
        Dstd: float = 0.52,
        pdf: Optional[np.ndarray] = None,
    ) -> np.ndarray:
        """
        Public wrapper — returns PSD array matching f.

        H may be a scalar; for time-series use, call in a loop or
        see inverse_bedload which iterates over H.
        """
        return self._psd(f, D, W, H, theta, r0, D50=D50, Dstd=Dstd, pdf=pdf)

    def inverse_depth(
        self,
        PSD_obs: np.ndarray,
        f: np.ndarray,
        D: Union[float, np.ndarray],
        W: float,
        theta: float,
        r0: float,
        H_bounds: tuple[float, float] = (0.01, 20.0),
        D50: Optional[float] = None,
        Dstd: float = 0.52,
        pdf: Optional[np.ndarray] = None,
        method: str = "brentq",
    ) -> np.ndarray:
        '''
        Invert observed PSD to flow depth H (turbulence model).

        For each time step, finds H such that median(PSD_turb(H)) == PSD_obs.
        PSD_obs is expected in dB (10*log10 scale), consistent with inverse_bedload
        in the other models.

        Parameters
        ----------
        PSD_obs  : observed PSD time series [dB], shape (n_times,)
        f        : frequency array [Hz]
        D        : grain diameter(s) [m]
        W        : channel width [m]
        theta    : channel slope [degrees]
        r0       : sensor distance [m]
        H_bounds : (H_min, H_max) search bracket [m]
        D50      : median grain size [m]
        Dstd     : log-space width of raised-cosine grain PDF
        pdf      : explicit grain-size PDF array
        method   : root-finding method — 'brentq' (default) or 'minimize_scalar'

        Returns
        -------
        H_est : estimated flow depth array, shape (n_times,)
        '''
        from scipy.optimize import brentq, minimize_scalar

        PSD_obs = np.asarray(PSD_obs)
        PSD_obs_lin = 10 ** (PSD_obs / 10)
        H_est = np.zeros(len(PSD_obs))

        for i, psd_target in enumerate(PSD_obs_lin):

            def residual(H):
                PSD_turb = self._psd(f, D, W, H, theta, r0,
                                     D50=D50, Dstd=Dstd, pdf=pdf)
                return np.median(PSD_turb) - psd_target

            if method == "brentq":
                try:
                    H_est[i] = brentq(residual, *H_bounds, xtol=1e-4)
                except ValueError:
                    # bracket does not straddle zero — target outside model range
                    H_est[i] = np.nan
            elif method == "minimize_scalar":
                result = minimize_scalar(
                    lambda H: residual(H) ** 2,
                    bounds=H_bounds,
                    method="bounded",
                )
                H_est[i] = result.x
            else:
                raise ValueError(f"Unknown method: {method}")

        return H_est